// Generated by CoffeeScript 1.8.0
var Sequencer,
  __bind = function(fn, me){ return function(){ return fn.apply(me, arguments); }; };

module.exports = Sequencer = (function() {
  function Sequencer() {
    this.ready = __bind(this.ready, this);
    this.exec = __bind(this.exec, this);
    this._next = __bind(this._next, this);
    this._queue = [];
    this._inprogress = false;
    this._ready = [];
  }

  Sequencer.prototype._next = function() {
    var item;
    this._inprogress = true;
    if (this._queue.length === 0) {
      if (this._ready.length === 0) {
        return this._inprogress = false;
      }
      this._queue.push({
        description: 'ready',
        action: this._ready.shift()
      });
    }
    item = this._queue.shift();
    return item.action((function(_this) {
      return function() {
        if (item.callback != null) {
          item.callback();
        }
        return _this._next();
      };
    })(this));
  };

  Sequencer.prototype.exec = function(description, action, cb) {
    this._queue.push({
      description: description,
      action: action,
      callback: cb
    });
    if (!this._inprogress) {
      return this._next();
    }
  };

  Sequencer.prototype.ready = function(callback) {
    if (!this._inprogress) {
      return callback(function() {});
    }
    return this._ready.push(callback);
  };

  return Sequencer;

})();
